### ISSUE TITLE
Todos page gives a JSON parsing error

### ISSUE THREAD

**Issue by nberlette** [mikenikles/sveltekit-prisma#10]
## The issue

Since they say a picture's worth a thousand words, here ya go...

![sveltekit-prisma-error](https://user-images.githubusercontent.com/11234104/141833626-02f5ffb9-10be-4abd-a643-4fc69bf0f032.png)

## The error

Upon further inspection, since I'm pretty familiar with the default (non-prisma) `sveltekit-todos` template myself, I checked out [`sveltekit-prisma.vercel.app/todos.json`](https://sveltekit-prisma.vercel.app/todos.json), and came across this wonderful little bit of err:

```
Can't reach database server at `containers-us-west-4.railway.app`:`6306`

Please make sure your database server is running at `containers-us-west-4.railway.app`:`6306`.
```

Maybe that will help. Unfortunately I'm practically running out the door right now or I'd dive into the code some more.

Thanks!!

## System Specs

**Device:** Macbook Pro (dinosaur model)
**OS**: macOS 10.15 Catalina
**Browser:** Chrome (latest)
**Coffee:** Fair-trade

**Comment by mikenikles** [comment]
I used a free Postgres DB on Railway and it only runs for 7 days. To make sure that was indeed the issue, I spun up a new instance which now runs for 7 days.

![image](https://user-images.githubusercontent.com/788827/141837193-af93447f-6675-4342-a84b-c67fae449dba.png)

**Comment by mikenikles** [comment]
In hindsight, I should probably upgrade to a paid plan and keep it running. Let me look into that :)

**Comment by nberlette** [comment]
Sorry I didn't see your replies until now! On the topic of Postgres providers... I'm sure you've already heard of it, but [Supabase.io](https://supabase.io) is pretty legit. I've been trying out the free tier for a couple months and it's been a breeze so far.

The community's a bit sparse as far as available Svelte / SvelteKit starters though... I've been meaning to whip one up myself but just haven't had the time
